// Generated by https://quicktype.io

export interface LoginQuery {
  data: Data;
}

interface Data {
  msg: Msg;
}

interface Msg {
  tokenAcess: string;
  idcliente: number;
  cliente: string;
  alias: string;
  correo: string;
  idperfil: number;
}
