// Generated by https://quicktype.io

export interface SingupForm {
    nombre:     string;
    alias:      string;
    mail:       string;
    password:   string;
    repassword: string;
    referido?:   string;
}
